// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7ANc1mSmro-VY2UaggDB2I0sBQ3epZ2c',
    appId: '1:584457763121:web:92063fc3bfdb09ccc8d810',
    messagingSenderId: '584457763121',
    projectId: 'storykitchen-af260',
    authDomain: 'storykitchen-af260.firebaseapp.com',
    storageBucket: 'storykitchen-af260.firebasestorage.app',
    measurementId: 'G-1FRGRKBFWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6CDIyS0Ymebyl_l1pFczQ3MbvWSvoIx8',
    appId: '1:584457763121:android:544c4eff64fef774c8d810',
    messagingSenderId: '584457763121',
    projectId: 'storykitchen-af260',
    storageBucket: 'storykitchen-af260.firebasestorage.app',
  );
}
